"""Reconciler agent — merges all topic summaries into a daily briefing.

Reads all files in output/topics/ and combines them into a single
output/daily_briefing.md file.

TODO: Replace with an LLM that produces a polished, coherent briefing
from the raw topic summaries.
"""

import time
from pathlib import Path

from conductor.executor.base import AgentExecutor, ExecutionContext, ExecutionResult
from conductor.models.ticket import Ticket


class ReconcilerAgent(AgentExecutor):
    @property
    def agent_name(self) -> str:
        return "reconciler_agent"

    def execute(self, ticket: Ticket, context: ExecutionContext) -> ExecutionResult:
        time.sleep(5)

        # Read all topic files
        topics_dir = Path(context.working_directory) / "output" / "topics"
        sections = []

        if topics_dir.exists():
            for topic_file in sorted(topics_dir.glob("*.md")):
                content = topic_file.read_text(encoding="utf-8")
                sections.append(content)

        # Also check input_dependencies from ticket metadata
        for dep_path in ticket.metadata.input_dependencies:
            full_path = Path(context.working_directory) / dep_path
            if full_path.exists() and full_path.is_file():
                content = full_path.read_text(encoding="utf-8")
                if content not in sections:
                    sections.append(content)

        # Extract city from ticket description
        city = "Unknown"
        for line in ticket.description.splitlines():
            if line.startswith("**City**:"):
                city = line.split(":", 1)[1].strip()

        # Build the merged briefing
        briefing = f"# 📰 Daily Briefing — {city}\n\n"
        briefing += f"*Generated by Conductor*\n\n"
        briefing += "---\n\n"

        if sections:
            briefing += "\n\n---\n\n".join(sections)
        else:
            briefing += "*No topic summaries found.*\n"

        briefing += "\n\n---\n\n*End of briefing.*\n"

        # Write the merged output
        created = []
        for path_str in ticket.metadata.deliverable_paths:
            full_path = Path(context.working_directory) / path_str
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(briefing, encoding="utf-8")
            created.append(path_str)

        return ExecutionResult(
            success=True,
            summary=f"Daily briefing for {city}: merged {len(sections)} topic(s)",
            deliverables_produced=created,
        )
